### ISSUE TITLE
Organización de los componentes

### ISSUE THREAD

**Issue by vdrg** [ACM-Planner/planner#4]
Hola :smile: !

Hey cabros no les tinca ordenar los componentes por funcionalidad en vez de tenerlos por separado? Onda Curriculum y CurriculumPanel podrían estar en el mismo directorio (a menos que uno de ellos lo vayan a usar después en otro componente). Lo digo porque de a poco se va a ir llenando de componentes y van a tener que ir saltando de componente en componente (siguiendo los imports).

Y después pueden juntar todo en un mismo index y exportar el componente principal.

**Comment by lopezjurip** [comment]
yo creo que en ese caso del Curriculum y CurriculumPanel, y en todo otro caso donde no vayamos a re-utilizar el componente sería bueno eso 👍

Esperemos hacer un merge y ordenar lo que hicimos ayer para que hayan menos conflictos
